server:
  port: 8080
spring:
  datasource:
    druid:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/ssmtest
     username: root
     password: 18603336220
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl